<?php
// $Id: fontsize.module,v 1.6 2005/04/01 00:07:23 drumm Exp $

/**
 * Implementation of hook_help()
 */
function fontsize_help($section) {
  switch ($section) {
    case 'admin/modules#description':
      return t('Creates a block allowing visitors to change the site\'s font size.');
  }
}

/**
 * Implementation of hook_menu()
 */
function fontsize_menu() {
  drupal_set_html_head('<link rel="alternate stylesheet" type="text/css" href="modules/fontsize/normal.css" title="normal" />' . "\n".
    '<link rel="alternate stylesheet" type="text/css" href="modules/fontsize/larger.css" title="larger" />'."\n".
    '<link rel="alternate stylesheet" type="text/css" href="modules/fontsize/smaller.css" title="smaller" />'."\n".
    '<script language="JavaScript" src="modules/fontsize/styleswitcher.js" type="text/javascript"> </script>');
}

/**
 * Implementation of hook_block()
 */
function fontsize_block($op = 'list', $delta = 0) {
  if ($op == 'list') {
    $blocks[0]['info'] = 'Change text size';
    return $blocks;
  }
  elseif ($op == 'view') {
    switch($delta) {
      case 0:
        $block['subject'] = t('Change text size');
        $block['content'] = theme('links', array('<a href="javascript:;" onclick="setActiveStyleSheet(\'larger\'); return false;" style="font-size: 120%; vertical-align: text-bottom;" class="larger">A</a>', '<a href="javascript:;" onclick="setActiveStyleSheet(\'normal\'); return false;" style="font-size: 100%; vertical-align: text-bottom;" class="normal">A</a>'), ' ');
        return $block;
    }
  }
}

?>
