<?php
function dictionary_menu($may_cache) {
  if ($may_cache) {
    $items[] = array('path' => 'dictionary', 'title' => t("dictionary"), 'callback' => 'dictionary_page', 'access' => user_access('access content'), 'type' => 'MENU_SUGGESTED_ITEM');
  }
  return $items ? $items : array();
}

function dictionary_page( $type = "" ) { 
//    global $theme;
   
    $keys = isset($_GET["Word"]) ? $_GET["Word"] : $_POST["Word"];
    $dict = isset($_GET["Dictionary"]) ? $_GET["Dictionary"] : $_POST["Dictionary"];


    switch ($dict) {
//      case "dvbc":
        // header("Location: http://dcvb.iecat.net/results.asp?Word=". htmlentities($keys, ENT_COMPAT, "UTF-8") );
        // header("Location: http://dcvb.iecat.net/results.asp?Word=". iconv("UTF-8", "ISO-8859-1", $keys) );
//        header("Location: http://dcvb.iecat.net/results.asp?txtWord=". catalan_filter($keys) );
//	break;
      case "dlc":
        // header("Location: http://pdl.iec.es/entrada/resultats_DIEC.asp?txtSearch=". recode_string("UTF-8..ISO-8859-1",$keys) );
        // header("Location: http://pdl.iec.es/entrada/resultats_DIEC.asp?txtSearch=". htmlentities($keys, ENT_COMPAT, "UTF-8") );
        // header("Location: http://pdl.iec.es/entrada/resultats_DIEC.asp?txtSearch=". $keys );
        // header("Location: http://pdl.iec.es/entrada/resultats_DIEC.asp?txtSearch=". catalan_filter($keys) );
	if (function_exists('recode_string'))
          header("Location: http://pdl.iec.es/entrada/resultats_DIEC.asp?txtSearch=". recode_string("UTF-8..ISO-8859-1",$keys) );
	else if (function_exists('iconv'))
          header("Location: http://pdl.iec.es/entrada/resultats_DIEC.asp?txtSearch=". iconv("UTF-8","ISO-8859-1",$keys) );
	else if (function_exists('mb_convert_encoding'))
          header("Location: http://pdl.iec.es/entrada/resultats_DIEC.asp?txtSearch=". mb_convert_encoding( $keys, "ISO-8859-1", "UTF-8") );
	else
          header("Location: http://pdl.iec.es/entrada/resultats_DIEC.asp?txtSearch=". $keys );
	break;
      default:
//        $theme->header();
        $output = "Posem a la teva disposició enllaços a aquests diccionaris per facilitar la consulta sobre una paraula en concret.<br>";
	$output .= "<h2>Instruccions per fer servir els diccionaris</h2>Si fas servir el diccionari en línia (DIEC), escriu la paraula i clica al botó \"cercar\". Tot seguit el navegador t'obrirà una nova finestra que et porta al resultat de la consulta en el diccionari.<br>Si fas servir un diccionari enllaçat, clica sobre el títol del diccionari i el navegador t'obrirà una fienstra on podràs fer la cerca.<br><br><br>";
	$output .="<div class=node><div class=title><b>En línia</b></div><div class=content><ul><li class\"leaf\">";
	$output .= " <h2>Diccionari de l'Institut d'Estudis Catalans (DIEC)</h2>És el normatiu, podriem dir que per tant, l'\"oficial\" per a la llengua catalana.";
	$output .= "</li></ul>";
        $output .= dictionary_page_form();
	$output .= "</div></div><br><br>";
	$output .= "<div class=node><div class=title><b>Enllaços</b></div><div class=content><ul><li class=\"leaf\">";
        $output .= "<a href=\"http://dcvb.iecat.net\" target=\"_blank\"><h2>Diccionari català-valencià-balear (DCVB)</a> d’A. M. Alcover i F. de B. Moll</h2>És una obra comprensiva de la llengua que es parla \"al Principat de Catalunya, al Regne de València, a les illes Balears, al departament francès dels Pirineus Orientals, a les Valls d'Andorra, al marge oriental d'Aragó i a la ciutat d'Alguer de Sardenya\". Està més orientat a recollir les variants dialectals.<br> Les transcripcions fonètiques es representen d’acord amb els principis de l’AFI (Associació Fonètica Internacional) adaptats al català per l’IEC, i la representació dels ètims àrabs s'ha adaptat als criteris de transliteració de l'IEC.";
	$output .= "</li><li class=\"leaf\">";
        $output .= "<a href=\"http://www.termcat.net/cercaterm/\" target=\"_blank\"><h2>Termcat</a> (cercaterm)</h2>Servei de consultes en línia del Termcat.<br>El TERMCAT té per finalitat la promoció, l'elaboració i la difusió de recursos terminològics, la normalització dels neologismes catalans i la prestació de serveis d'assessorament per facilitar l'ús de la llengua en els àmbits científics, tècnics i socioeconòmics.<br>Creat el 1985, és un consorci integrat per la Generalitat de Catalunya, l'Institut d'Estudis Catalans i el Consorci per a la Normalització Lingüística.";
	$output .= "</li></ul></div></div>";
	$output .= "<br><small>Aquesta web només proporciona un enllaç extern a la versió electrònica d'aquests diccionaris disponibles a la xarxa. No hi està vinculada de cap manera ni conté cap dels seus continguts.<small>";
//        $theme->box(variable_get("dictionary_title", t("Diccionaris")), $output);
//        $theme->footer();
}


        return print theme('page', $output);
}

// function catalan_filter($in) {
//   
//  $out = strtolower($in);
//  
//  $out = str_replace("à", "%e0",$out);
//  $out = str_replace("è", "%e8",$out);
//  $out = str_replace("é", "%e9",$out);
//  $out = str_replace("í", "%ed",$out);
//  $out = str_replace("ò", "%f2",$out);
//  $out = str_replace("ó", "%f3",$out);
//  $out = str_replace("ú", "%fa",$out);
//  $out = str_replace("ë", "%eb",$out);
//  $out = str_replace("ï", "%ef",$out);
//  $out = str_replace("ü", "%fc",$out);
//  $out = str_replace("ç", "%e7",$out);
//  $out = str_replace("ñ", "%f1",$out);
//  $out = str_replace("·", "%b7",$out);

//  return $out;
//}


function dictionary_block($op = "list", $delta = 0) {

  if ($op == "list") {
    $blocks[0]["info"] = variable_get("dictionary_title",t("Diccionaris"));
    return $blocks;
  }
  else {
//    $blocktitle = variable_get("dictionary_title","<a href=\"dictionary\">" .t("Diccionaris") ."</a>");
    $block['subject'] = variable_get("dictionary_title","<a href=\"dictionary\">" .t("Diccionaris") ."</a>");
    $block['content'] = dictionary_page_form();
    return $block;
//    return print theme("block", $blocktitle, dictionary_page_form() );
  }
}

function dictionary_page_form() {
    $form = "<form name=\"Cerca paraules als Diccionaris\" method=\"post\" target=\"_blank\" action=\"dictionary\" >";
//    $form .= "<p><label><input type=\"radio\" name=\"Dictionary\" value=\"dvbc\">Català-Valencià-Balear</label><br>";
    $form .= "<label><input type=\"hidden\" name=\"Dictionary\" value=\"dlc\" checked>Institut d'Estudis Catalans</label><br></p>";
    $form .= t("Paraula a cercar: ");
    $form .= "<input type=\"text\" name=\"Word\" size=\"15\" maxlength=\"30\">";
    $form .= "<br><input type=\"submit\" value=\"Enviar\"> </form>";


 return $form;
}

function dictionary_settings() {
  $output .= form_textfield("Titol del bloc", "dictionary_title", variable_get("dictionary_title", t("Diccionaris")), 35, 255, t("Títol de la capsa on apareixen el cercador de diccionaris..."));

 return $output;
}
?>
